version: '3.8'

volumes:
  static:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './static'
  nginx_templates:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './nginx_templates'
  postgres_db:

services:
  db:
    image: postgres:12.4
    container_name: postgres
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  yamdb:
    image: sovushkasever/api_yamdb:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    restart: always
    image: nginx:1.19
    container_name: webserver
    volumes:
      - static:/usr/share/nginx/html/static/
      - nginx_templates:/etc/nginx/templates
    ports:
      - "80:80"
    depends_on:
      - yamdb
    environment:
     - NGINX_PORT=80
     - NGINX_SERVERNAME=localhost
     - NGINX_UPSTREAM=http://yamdb:8000